image: node:lts

before_script:  
  - apt-get update -qq && apt-get install
  - apt install -y rsync
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - cat "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

#cache:
#  paths:
#    - node_modules/
#    - .yarn

stages:
  - build
  - deploy


build dev:
  stage: build
  only:
    - dev
  script:
    - cd bba-client
    - yarn
    - yarn generate
    - ls -la

deploy development:
  stage: deploy
  only:
    - dev
  script:
    - cd bba-client
    - sed -i "s/{COMMIT}/$CI_COMMIT_REF_SLUG $CI_COMMIT_SHORT_SHA/g" components/paradym/Navigation.vue
    - rsync -azh --rsh="ssh -o StrictHostKeyChecking=no -l ubuntu" ./../** ubuntu@18.220.145.253:/var/www/apps/dev/dev.mobile.bodhisys.io/
    - ssh -o StrictHostKeyChecking=no ubuntu@18.220.145.253 "cd /var/www/apps/dev/dev.mobile.bodhisys.io/bba-client; yarn; yarn generate; pm2 restart bikeapp"

deploy production:
  stage: deploy
  only:
    - main
  script:
    - cd bba-client
    - sed -i "s/{COMMIT}/$CI_COMMIT_REF_SLUG $CI_COMMIT_SHORT_SHA/g" components/paradym/Navigation.vue
    - rsync -azh --rsh="ssh -o StrictHostKeyChecking=no -l ubuntu" ./../** ubuntu@3.22.62.199:/home/ubuntu/bikeapp-copy
    - ssh -o StrictHostKeyChecking=no ubuntu@3.22.62.199 "cd /home/ubuntu/bikeapp-copy/bba-client; yarn; yarn generate; pm2 restart bikeapp"



