image: node:lts

before_script:
  - apt-get update -qq && apt-get install
  - apt install -y rsync
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
  - eval $(ssh-agent -s)
  - cat "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

stages:
  - build
  - deploy

build dev:
  stage: build
  only:
    - dev
  script:
    - cd bba-client
    - yarn
    - yarn generate
    - ls -la

build production:
  stage: build
  only:
    - main
  script:
    - cd bba-client
    - yarn
    - yarn generate
    - ls -la

deploy development:
  stage: deploy
  only:
    - dev
  script:
    - cd bba-client
    - sed -i "s/{COMMIT}/$CI_COMMIT_REF_SLUG $CI_COMMIT_SHORT_SHA/g" components/paradym/Navigation.vue
    - rsync -azh --rsh="ssh -o StrictHostKeyChecking=no -l gitlab" ./../** gitlab@192.168.13.158:/var/storage/apps/bodhisys/apps-dev/bikeapp-copy
    - ssh -o StrictHostKeyChecking=no gitlab@192.168.13.158 "cd /var/storage/apps/bodhisys/apps-dev/bikeapp-copy/bba-client; yarn; yarn generate;"
    - cd ..
    - cd bba-server
    - rsync -azh --rsh="ssh -o StrictHostKeyChecking=no -l gitlab" ./../** gitlab@192.168.13.158:/var/storage/apps/bodhisys/apps-dev/bikeapp-server
    - ssh -o StrictHostKeyChecking=no gitlab@192.168.13.158 "cd /var/storage/apps/bodhisys/apps-dev/bikeapp-copy/bba-server; yarn;"
    - ls -la ./..

deploy production:
  stage: deploy
  only:
    - main
  script:
    - cd bba-client
    - sed -i "s/{COMMIT}/$CI_COMMIT_REF_SLUG $CI_COMMIT_SHORT_SHA/g" components/paradym/Navigation.vue
    - rsync -azh --rsh="ssh -o StrictHostKeyChecking=no -l gitlab" ./../** gitlab@192.168.13.158:/var/storage/apps/bodhisys/apps/bikeapp-copy
    - ssh -o StrictHostKeyChecking=no gitlab@192.168.13.158 "cd /var/storage/apps/bodhisys/apps/bikeapp-copy/bba-client; yarn; yarn generate;"
    - cd ..
    - cd bba-server
    - rsync -azh --rsh="ssh -o StrictHostKeyChecking=no -l gitlab" ./../** gitlab@192.168.13.158:/var/storage/apps/bodhisys/apps/bikeapp-server
    - ssh -o StrictHostKeyChecking=no gitlab@192.168.13.158 "cd /var/storage/apps/bodhisys/apps/bikeapp-copy/bba-server; yarn;"
    - ls -la ./..